apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: mongodb-pvc
      containers:
        - name: mongodb
          image: mongo:7.0
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
          ports:
            - containerPort: 27017
          envFrom:
            - configMapRef:
                name: expense-tracker-config
      initContainers:
        - name: init-seed
          image: mongo:7.0
          command: ['mongosh']
          args:
            - "--eval"
            - >
              db = connect('mongodb://monogodb:27017/expense-tracker');
              db.categories.insertMany([
                { "label": "Groceries", "color": "#FFEB3B", "type": "expense" },
                { "label": "Dining Out", "color": "#FF5722", "type": "expense" },
                { "label": "Rent/Mortgage", "color": "#4CAF50", "type": "expense" },
                { "label": "Transportation", "color": "#03A9F4", "type": "expense" },
                { "label": "Healthcare", "color": "#8BC34A", "type": "expense" },
                { "label": "Entertainment", "color": "#9C27B0", "type": "expense" },
                { "label": "Income", "color": "#00BCD4", "type": "income" },
                { "label": "Salary", "color": "#009688", "type": "income" },
                { "label": "Business Income", "color": "#FFC107", "type": "income" },
                { "label": "Investment Income", "color": "#FF9800", "type": "income" }
              ]);
