apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-scripts
  namespace: default  # Adjust if you're using a different namespace
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS expense_manager;
